version: '3'

services:
  db:
    image: mysql:8.0
    env_file:
      - src/main/resources/.env
    environment:
      MYSQL_ROOT_PASSWORD: ${INTEGRATION_ROOT_PASSWORD}
      MYSQL_DATABASE: ${INTEGRATION_DATABASE}
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - my-db-data:/var/lib/mysql
    ports:
      - "127.0.0.1:3307:3306"
      # make sure that your port connection in mysql is 3307

volumes:
  my-db-data: