// get all organisers
GET http://localhost:8080/api/v1/organisers
Authorization: Basic admin@admin.com admin

###

// get organiser by email
POST http://localhost:8080/api/v1/organisers/email/
Content-Type: application/json
Authorization: Basic admin@admin.com admin 

{
    "email": "bul.ge@gmai.com"
}

###

// get events by Organiser email
POST http://localhost:8080/api/v1/organisers/email/events
Content-Type: application/json
Authorization: Basic admin@admin.com admin

{
    "email": "org@org.com"
}

###

POST http://localhost:8080/api/v1/organisers/create-event
Content-Type: application/json
Authorization: Basic admin@admin.com admin

{
    "name":"helo",
    "description":" weewoo wee woo huhahehea",
    "organiserId":1
}

###
POST http://localhost:8080/api/v1/organisers/create-event
Content-Type: application/json
Authorization: Basic org@org.com organiser

{
"capacity": 1,
"description": "sda a a a a  aa a a a a a a a ",
"endDateTime": "2023-10-19T16:00:00.000Z",
"minScore": 0,
"name": "asdasda",
"startDateTime": "2023-10-13T10:03:05.753Z",
"venue": "adadda"
}

###
DELETE  http://localhost:8080/api/v1/organisers/id/1
Content-Type: application/json
Authorization: Basic admin@admin.com admin

###

// allocate slots
POST http://localhost:8080/api/v1/organisers/events/allocation
Content-Type: application/json
Authorization: Basic org@org.com organiser

{
    "eventId":5,
    "algo":"Random"
}