// register
POST http://localhost:8080/api/v1/auth/signup
Content-Type: application/json

{
    "name":"thanos gay",
    "email":"thanos.gay@gmail.com",
    "password":"13473433",
    "matricNo":"23324269",
    "phone":"43563789"
}

###

// sign in
POST http://localhost:8080/api/v1/auth/signin
Content-Type: application/json

{
    "email":"thanos.gay@gmail.com",
    "password":"123"
}

###
