
// get registrations by studentid
GET http://localhost:8080/api/v1/register-event/student/1
Authorization: Basic bul.ge@gmail.com 13473433
###

//get registrations by eventid
GET http://localhost:8080/api/v1/register-event/event/2
Authorization: Basic bul.ge@gmail.com 13473433

###

// get registration by studentId and eventId
GET http://localhost:8080/api/v1/register-event/event/2/student/1
Authorization: Basic admin@admin.com admin

###

// updates status of application
PUT http://localhost:8080/api/v1/register-event/update
Content-Type: application/json
Authorization: Basic bul.ge@gmail.com 13473433

{
    "studentId":1,
    "eventId":1,
    "status":"ACCEPTED"
}

###

// updates attendance 
PUT http://localhost:8080/api/v1/register-event/update
Content-Type: application/json
Authorization: Basic admin@admin.com admin

{
    "studentId":1,
    "eventId":1,
    "presentForEvent":false
}

###

// updates event registration 
PUT http://localhost:8080/api/v1/register-event/update
Content-Type: application/json
Authorization: Basic admin@admin.com admin

{
    "studentId":1,
    "eventId":1,
    "status":"ACCEPTED",
    "presentForEvent":true
}

###
// post a new registration (only need eventId, and signed in as student)
POST http://localhost:8080/api/v1/register-event
Content-Type: application/json
Authorization: Basic bul.ge@gmail.com 13473433

{
    "eventId":1
}

###

// post a new registration (only need eventId, and signed in as student)
POST http://localhost:8080/api/v1/register-event
Content-Type: application/json
Authorization: Basic admin@admin.com admin

{
    "studentId":3,
    "eventId":5
}

###

// delete by id
DELETE http://localhost:8080/api/v1/register-event/id/1
Authorization: Basic admin@admin.com admin