
// get registrations by userid
GET http://localhost:8080/api/v1/register/student/1
Authorization: Basic admin admin
###

//get registrations by eventid
GET http://localhost:8080/api/v1/register/event/1

###

// post a new registration
POST http://localhost:8080/api/v1/register
Content-Type: application/json
Authorization: Basic admin admin

{
    "studentId":1,
    "eventId":2,
    "isDeregistered":false,
    "isSuccessful":false
}

###

// delete by id
DELETE http://localhost:8080/api/v1/register/id/2