// get all users
GET http://localhost:8080/api/v1/users

###

// get specific user
GET http://localhost:8080/api/v1/users/4

###

// post a new user
POST http://localhost:8080/api/v1/users
Content-Type: application/json

{"userId":5,"name":"chee bhai","password":"123","email":"knn.ccb@gmail.com","phone":25743324,"dob":"2001-02-04"}

###

PUT http://localhost:8080/api/v1/users/2
Content-Type: application/json

{"name":"bi ceps","password":"123","email":"fom.oris@gmail.com","phone":43257412,"dob":"2001-11-04"}

###