// get all users
GET http://localhost:8080/api/v1/students
Authorization: Basic admin@admin.com admin


###

// get specific user by id
GET http://localhost:8080/api/v1/students/id/2
Authorization: Basic admin@admin.com admin

###

// get specific user by email
GET http://localhost:8080/api/v1/students/email/admin@admin.com
Authorization: Basic admin@admin.com admin

###

// get specific users by name
GET http://localhost:8080/api/v1/students/name/john%20weak
Authorization: Basic admin@admin.com admin

###

// get registered events by email
GET http://localhost:8080/api/v1/students/email/admin@admin.com/registered
Authorization: Basic admin@admin.com admin

###

// get registered events by email and status
GET http://localhost:8080/api/v1/students/email/admin@admin.com/registered/ACCEPTED
Authorization: Basic admin@admin.com admin

###

// post a new user fail due to not meeting validation constraints
POST http://localhost:8080/api/v1/students
Content-Type: application/json
Authorization: Basic admin@admin.com admin

{
    "name":"supper man",
    "password":"5378967867",
    "email":"man.bat@gmail.com",
    "matricNo": "6908908785",
    "phone":"25743324",
    "dob":"2001-02-04",
    "accType":"U",
    "image":"random/path",
    "role":"USER"
}

###

// post a new user successfully
POST http://localhost:8080/api/v1/students
Content-Type: application/json
Authorization: Basic admin@admin.com admin

{
    "name":"john weak",
    "password":"78967967",
    "email":"jonathan.weak@gmail.com",
    "matricNo": "12369323",
    "phone":"62226111",
    "dob":"2001-02-01",
    "accType":"S",
    "image":"random/path",
    "role":"USER"
}

###

PUT http://localhost:8080/api/v1/students/id/2
Content-Type: application/json
Authorization: Basic admin@admin.com admin

{
    "phone":86931904
}

###

// delete
DELETE http://localhost:8080/api/v1/students/id/4
