// register a user
POST http://localhost:8080/api/v1/auth/register
Authorization: Basic admin@admin.com admin
Content-Type: application/json

{
    "name":"thanos gay",
    "email":"justintyf@hotmail.com",
    "password":"13473433",
    "matricNo":"23324269",
    "phone":"43563789",
    "userType": "O"
}

###

// forget password send token
POST http://localhost:8080/api/v1/forgot-password/token
Authorization: Basic admin@admin.com admin
Content-Type: application/json

{
    "email":"justintyf@hotmail.com"
}

###

// reset password
POST http://localhost:8080/api/v1/forgot-password/
Authorization: Basic admin@admin.com admin
Content-Type: application/json

{
    "email":"justintyf@hotmail.com",
    "resetPasswordToken": "VunIvvr7gEIqbNfO",
    "newPassword":"12345678"

    
}

###
