// register
POST http://localhost:8080/api/v1/auth/register
Content-Type: application/json

{
    "name":"thanos gay",
    "email":"thanos.gay@gmail.com",
    "password":"12345678",
    "userType": "S",
    "matricNo":"12345678",
    "phone":"12345678"
}

###

// sign in
POST http://localhost:8080/api/v1/auth/login
Content-Type: application/json

{
    "email":"justintyf@hotmail.com",
    "password":"12345678"
}

###

POST http://localhost:8080/api/v1/auth/register
Content-Type: application/json

{
    "name":"jimin's bulge",
    "email":"bul.ge@gmail.com",
    "password":"13473433",
    "matricNo":"23324269",
    "phone":"43563789",
    "userType": "O"
}

###

// sign in
POST http://localhost:8080/api/v1/auth/login
Content-Type: application/json

{
    "email":"bul.ge@gmail.com",
    "password":"13473433"
}

###

// register
POST http://localhost:8080/api/v1/auth/register
Content-Type: application/json

{
    "name":"thanos gay1",
    "email":"thanos.gay1@gmail.com",
    "password":"12345678",
    "userType": "S"
}

###
// register
POST http://localhost:8080/api/v1/auth/register
Content-Type: application/json

{
    "name":"thanos gay2",
    "email":"thanos.gay2@gmail.com",
    "password":"12345678",
    "userType": "S"
}

###

// register
POST http://localhost:8080/api/v1/auth/register
Content-Type: application/json

{
    "name":"thanos gay3",
    "email":"thanos.gay3@gmail.com",
    "password":"12345678",
    "userType": "S"
}
