// get all users
GET http://localhost:8080/api/v1/users

###

// get specific user
GET http://localhost:8080/api/v1/users/2

###

// post a new user
POST http://localhost:8080/api/v1/users
Content-Type: application/json

{"name":"chee bhai","password":"123","email":"knn.ccb@gmail.com","phone":25743324,"dob":"2001-02-04"}

###

PUT http://localhost:8080/api/v1/users/4
Content-Type: application/json

{"name":"bi ceps","password":"321","email":"fom.oris@gmail.com","dob":"2001-11-04"}

###
// get all events
GET http://localhost:8080/api/v1/events

###

// get specific event
GET http://localhost:8080/api/v1/events/1

###

// update event
PUT http://localhost:8080/api/v1/events/2
Content-Type: application/json

{
    "name":"CS201",
    "startDate":"2001-02-04",
    "endDate":"2001-08-10",
    "description":"Data Structures and Algorithm",
    "capacity":45,
    "eventType":"Workshop",
    "venue":"venue",
    "registered": false,
    "visible": false
}

###

// post a new event
POST http://localhost:8080/api/v1/events
Content-Type: application/json

{
    "name":"CS203",
    "startDate":"2001-02-04",
    "endDate":"2001-08-04",
    "description":"Collaborative Software Programming",
    "capacity":45,
    "eventType":"Workshop",
    "venue":"venue",
    "registered": false,
    "visible": false
}