version: '3'

services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${INTEGRATION_ROOT_PASSWORD}
      MYSQL_DATABASE: ${INTEGRATION_DATABASE}
    volumes:
      - my-db-data:/var/lib/mysql
    ports:
      - "127.0.0.1:3306:3306"

volumes:
  my-db-data: