# This workflow creates the backend Docker image and push it to AWS ECR. It will then deploy a task definition
# to ECS to run the backend container. 

name: Backend Deployment

on:
  push:
    branches:
      - main

env:
  AWS_REGION: ap-southeast-1 
  ECR_REPOSITORY: public.ecr.aws/d5r5w0o4/openjio-backend-v2
  ECS_SERVICE: backendService # set this to your Amazon ECS service name
  ECS_CLUSTER:
    openjio # set this to your Amazon ECS cluster name
    # file, e.g. .aws/task-definition.json
  CONTAINER_NAME:
    openjio-backend # set this to the name of the container in the
    # containerDefinitions section of your task definition

permissions:
  contents: read

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Change directory to Backend 
        run: cd jio

      - name: Build, tag, and push image to Amazon ECR
        id: build-image
        env:
          IMAGE_TAG: latest
        run: |
          aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws/d5r5w0o4
          docker build -t $ECR_REPOSITORY:$IMAGE_TAG .
          docker push $ECR_REPOSITORY:$IMAGE_TAG
          echo "::set-output name=image::$ECR_REPOSITORY:$IMAGE_TAG"
          aws ecs update-service --cluster $ECS_CLUSTER --service $ECS_SERVICE --force-new-deployment
