name: Backend CI/CD

on:
  push:
    branches:
      - main

env:
  AWS_REGION: ap-southeast-1
  ECR_REPOSITORY: public.ecr.aws/d5r5w0o4/openjio-backend-v2 
  ECS_SERVICE: backendService
  ECS_CLUSTER: openjio
  CONTAINER_NAME: openjio-backend
  INTEGRATION_DATABASE: openjio1

permissions:
  contents: read
  id-token: write # Required for OIDC

jobs:
  testing:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Start MySQL instance
        env:
          INTEGRATION_ROOT_PASSWORD: ${{ secrets.INTEGRATION_ROOT_PASSWORD }}
          INTEGRATION_DATABASE: ${{ env.INTEGRATION_DATABASE }}
        run: |
          cd jio
          docker-compose -f docker-compose.yml up -d db
          echo 'Waiting for the database service to be fully ready...'
          while ! docker-compose -f docker-compose.yml ps | grep 'db' | grep 'healthy'; do
            sleep 10
            echo 'Waiting for the database to become healthy...'
          done
          echo 'Database service is up and running!'

      - name: Run unit and integration tests on Spring Boot application 
      # environment variables will be configured to run the Test DB
        env:
          DATABASE_NAME: ${{ env.INTEGRATION_DATABASE }}
          DATABASE_HOST: ${{ secrets.DATABASE_HOST }}
          DATABASE_USERNAME: ${{ secrets.DATABASE_USERNAME }}
          DATABASE_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}
        run: |
          cd jio
          echo "Running Spring Boot..."
          ./mvnw test

      - name: Shutdown MySQL service
        if: always()
        run: |
          cd jio
          docker-compose -f docker-compose.yml down

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Build, tag, and push image to Amazon ECR
        id: build-image
        env:
          IMAGE_TAG: ${{ github.sha }}
        run: |
          cd frontend
          aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws/d5r5w0o4
          docker build -t $ECR_REPOSITORY:$IMAGE_TAG .
          docker push $ECR_REPOSITORY:$IMAGE_TAG
          echo "::set-output name=image::$ECR_REPOSITORY:$IMAGE_TAG"

# This workflow creates the backend Docker image and push it to AWS ECR. It will then deploy a task definition
# to ECS to run the backend container. 

# name: Backend Deployment

# on:
#   push:
#     branches:
#       - pauseCICD

# env:
#   AWS_REGION: ap-southeast-1 
#   ECR_REPOSITORY: public.ecr.aws/d5r5w0o4/openjio-backend-v2
#   ECS_SERVICE: backendService # set this to your Amazon ECS service name
#   ECS_CLUSTER:
#     openjio # set this to your Amazon ECS cluster name
#     # file, e.g. .aws/task-definition.json
#   CONTAINER_NAME:
#     openjio-backend # set this to the name of the container in the
#     # containerDefinitions section of your task definition

# permissions:
#   contents: read

# jobs:
#   deploy:
#     name: Deploy
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout
#         uses: actions/checkout@v3

#       - name: Configure AWS credentials
#         uses: aws-actions/configure-aws-credentials@v1
#         with:
#           aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
#           aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#           aws-region: ${{ env.AWS_REGION }}

#       # - name: Change directory to Backend 
#       #   run: cd jio

#       - name: Build, tag, and push image to Amazon ECR
#         id: build-image
#         env:
#           IMAGE_TAG: latest
#         run: |
#           cd jio
#           aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws/d5r5w0o4
#           docker build -t $ECR_REPOSITORY:$IMAGE_TAG .
#           docker push $ECR_REPOSITORY:$IMAGE_TAG
#           echo "::set-output name=image::$ECR_REPOSITORY:$IMAGE_TAG"
#           aws ecs update-service --cluster $ECS_CLUSTER --service $ECS_SERVICE --force-new-deployment
