# This workflow creates the frontend Docker image and push it to AWS ECR. It will then deploy a task definition
# to ECS to run the frontend container. 

name: Frontend Deployment

on:
  push:
    branches:
      - main

env:
  AWS_REGION: ap-southeast-1 
  ECR_REPOSITORY: public.ecr.aws/d5r5w0o4/openjio-frontend-v2 
  ECS_SERVICE: frontendService # set this to your Amazon ECS service name
  ECS_CLUSTER: openjio # set this to your Amazon ECS cluster name
  CONTAINER_NAME: openjio-frontend # set this to the name of the container in the containerDefinitions section of your task definition

permissions:
  contents: read

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Build, tag, and push image to Amazon ECR
        id: build-image
        env:
          IMAGE_TAG: ${{ github.sha }}
        run: |
          cd frontend
          aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws/d5r5w0o4
          docker build -t $ECR_REPOSITORY:$IMAGE_TAG .
          docker push $ECR_REPOSITORY:$IMAGE_TAG
          echo "::set-output name=image::$ECR_REPOSITORY:$IMAGE_TAG"

      - name: Install jq
        run: sudo apt-get install jq

      - name: Fill in the new image ID in the Amazon ECS task definition
        id: task-def
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          task-definition: task-definitions/deployFrontend-v2-revision9.json
          container-name: ${{ env.CONTAINER_NAME }}
          image: ${{ steps.build-image.outputs.image }}

      - name: Register new task definition
        id: register-task-def
        run: |
          NEW_TASK_DEF_JSON=$(aws ecs register-task-definition --cli-input-json file://task-definitions/deployFrontend-v2-revision9.json)
          NEW_TASK_DEF_ARN=$(echo $NEW_TASK_DEF_JSON | jq -r '.taskDefinition.taskDefinitionArn')
          echo "NEW_TASK_DEF_ARN=$NEW_TASK_DEF_ARN" >> $GITHUB_ENV
          echo "::set-output name=task_definition_arn::$NEW_TASK_DEF_ARN"

      - name: Deploy to Amazon ECS
        run: |
          aws ecs update-service --cluster ${{ env.ECS_CLUSTER }} --service ${{ env.ECS_SERVICE }} --task-definition ${{ steps.register-task-def.outputs.task_definition_arn }}
